// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using angularcore2.Models;

namespace angularcore2.Migrations
{
    [DbContext(typeof(angularcore2Context))]
    partial class angularcore2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("angularcore2.Models.LoginModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("LoginModels");
                });

            modelBuilder.Entity("angularcore2.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image1");

                    b.Property<string>("Image2");

                    b.Property<string>("Image3");

                    b.Property<string>("description");

                    b.Property<string>("price");

                    b.Property<string>("productGroup");

                    b.Property<string>("productName");

                    b.Property<string>("productTitle");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("angularcore2.Models.userAddressModels", b =>
                {
                    b.Property<int>("userAddressModelsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("area");

                    b.Property<int>("areaCode");

                    b.Property<int>("userModelsId");

                    b.HasKey("userAddressModelsId");

                    b.HasIndex("userModelsId");

                    b.ToTable("userAddressModels");
                });

            modelBuilder.Entity("angularcore2.Models.userModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("username");

                    b.Property<string>("userphone");

                    b.HasKey("Id");

                    b.ToTable("userModels");
                });

            modelBuilder.Entity("angularcore2.Models.userAddressModels", b =>
                {
                    b.HasOne("angularcore2.Models.userModels")
                        .WithMany("userAddress")
                        .HasForeignKey("userModelsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
